In [1]:
import env
from env import get_db_url
from pydataset import data

In [27]:
df_iris = data('iris')
df_iris.head(3)
df_iris.iloc[0:3]

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa

In [3]:
df_iris.shape

(150, 5)

In [4]:
df_iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [5]:
df_iris.dtypes

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species          object
dtype: object

In [30]:
stats = df_iris.describe().T
stats
#variables live a happier life as columns

              count      mean       std  min  25%   50%  75%  max
Sepal.Length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
Sepal.Width   150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4
Petal.Length  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9
Petal.Width   150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5

In [31]:
stats['range'] = stats['max'] - stats['min']
stats

              count      mean       std  min  25%   50%  75%  max  range
Sepal.Length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9    3.6
Sepal.Width   150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4    2.4
Petal.Length  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9    5.9
Petal.Width   150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5    2.4

## 5. Spreadsheets

In [7]:
import pandas as pd

In [20]:
df_google_sheets = pd.read_csv('telco_churn_new.csv')
df_google_sheets.head(100)

,Unnamed: 0,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,total_charges,churn,tenure
0,0,0002-ORFBO,Female,No,Yes,Yes,1 line,DSL,1 YR,Mailed check,65.60,593.30,No,9.0
1,1,0003-MKNFE,Male,No,No,No,2+ lines,DSL,Monthly,Mailed check,59.90,542.40,No,9.1
2,2,0004-TLHLJ,Male,No,No,No,1 line,Fiber,Monthly,Electronic check,73.90,280.85,Yes,3.8
3,3,0011-IGKFF,Male,Yes,Yes,No,1 line,Fiber,Monthly,Electronic check,98.00,1237.85,Yes,12.6
4,4,0013-EXCHZ,Female,Yes,Yes,No,1 line,Fiber,Monthly,Mailed check,83.90,267.40,Yes,3.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0164-APGRB,Female,No,No,No,2+ lines,Fiber,2 YR,Electronic check,114.90,8496.70,No,73.9
96,96,0164-XAIRP,Female,No,No,No,1 line,No plan,2 YR,Bank transfer (automatic),19.55,470.20,No,24.1
97,97,0168-XZKBB,Female,No,Yes,No,2+ lines,Fiber,Monthly,Electronic check,86.85,1564.40,No,18.0
98,98,0174-QRVVY,Male,No,Yes,Yes,2+ lines,No plan,2 YR,Credit card (automatic),25.35,1847.55,No,72.9
99,99,0177-PXBAT,Male,Yes,Yes,No,2+ lines,Fiber,Monthly,Bank transfer (automatic),109.90,3694.70,No,33.6

In [21]:
df_google_sheets_sample = df_google_sheets.head(100)
df_google_sheets_sample

,Unnamed: 0,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,total_charges,churn,tenure
0,0,0002-ORFBO,Female,No,Yes,Yes,1 line,DSL,1 YR,Mailed check,65.60,593.30,No,9.0
1,1,0003-MKNFE,Male,No,No,No,2+ lines,DSL,Monthly,Mailed check,59.90,542.40,No,9.1
2,2,0004-TLHLJ,Male,No,No,No,1 line,Fiber,Monthly,Electronic check,73.90,280.85,Yes,3.8
3,3,0011-IGKFF,Male,Yes,Yes,No,1 line,Fiber,Monthly,Electronic check,98.00,1237.85,Yes,12.6
4,4,0013-EXCHZ,Female,Yes,Yes,No,1 line,Fiber,Monthly,Mailed check,83.90,267.40,Yes,3.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0164-APGRB,Female,No,No,No,2+ lines,Fiber,2 YR,Electronic check,114.90,8496.70,No,73.9
96,96,0164-XAIRP,Female,No,No,No,1 line,No plan,2 YR,Bank transfer (automatic),19.55,470.20,No,24.1
97,97,0168-XZKBB,Female,No,Yes,No,2+ lines,Fiber,Monthly,Electronic check,86.85,1564.40,No,18.0
98,98,0174-QRVVY,Male,No,Yes,Yes,2+ lines,No plan,2 YR,Credit card (automatic),25.35,1847.55,No,72.9
99,99,0177-PXBAT,Male,Yes,Yes,No,2+ lines,Fiber,Monthly,Bank transfer (automatic),109.90,3694.70,No,33.6

In [22]:
df_google_sheets.size

98686

In [23]:
## Print the 5 column names:
df_google_sheets_sample.columns.values[0:5]

array(['Unnamed: 0', 'customer_id', 'gender', 'is_senior_citizen',
       'partner'], dtype=object)

In [24]:
## Print column names with dtype object:
list(df_google_sheets_sample.select_dtypes(['object']))

['customer_id',
 'gender',
 'is_senior_citizen',
 'partner',
 'dependents',
 'phone_service',
 'internet_service',
 'contract_type',
 'payment_type',
 'churn']

In [32]:
## compute range for each numeric column type:
float_columns_list = list(df_google_sheets_sample.select_dtypes(['float']))
float_columns_list

['monthly_charges', 'total_charges', 'tenure']

In [33]:
float_columns = df_google_sheets_sample.select_dtypes(['float'])
float_columns

    monthly_charges  total_charges  tenure
0             65.60         593.30     9.0
1             59.90         542.40     9.1
2             73.90         280.85     3.8
3             98.00        1237.85    12.6
4             83.90         267.40     3.2
5             69.40         571.45     8.2
6            109.70        7904.25    72.1
7             84.65        5377.80    63.5
8             48.20         340.35     7.1
9             90.45        5957.90    65.9
10            45.20        2460.55    54.4
11           116.80        8456.75    72.4
12            68.95         351.50     5.1
13           101.30        7261.25    71.7
14            45.05        2560.10    56.8
15            95.75        6849.40    71.5
16            61.25        1993.20    32.5
17            72.10          72.10     1.0
18            62.70        2791.50    44.5
19            25.10          25.10     1.0
20            25.20        1306.30    51.8
21            94.10        1215.60    12.9
22            83.75        1849.95    22.1
23            19.85          57.20     2.9
24            20.35          76.35     3.8
25            30.50          30.50     1.0
26           103.70        5656.75    54.5
27            20.40        1090.60    53.5
28            19.60         471.85    24.1
29            19.70        1396.90    70.9
30            91.20        3247.55    35.6
31            20.45         900.90    44.1
32           115.80        7942.15    68.6
33            20.55        1343.40    65.4
34            39.40         825.40    20.9
35            25.10        1070.15    42.6
36            89.80        4959.60    55.2
37            94.75        5597.65    59.1
38            20.30         224.50    11.1
39            75.75        1929.00    25.5
40            49.25          91.10     1.8
41            78.20        2078.95    26.6
42            25.50         630.60    24.7
43            61.60        1611.00    26.2
44            45.00        1242.45    27.6
45            85.15        6316.20    74.2
46            51.45         727.85    14.1
47            99.25        3532.00    35.6
48            44.30          44.30     1.0
49            94.20        2607.60    27.7
50            81.25        5567.55    68.5
51            99.95        3767.40    37.7
52            91.55        3673.60    40.1
53           104.50        4036.85    38.6
54            95.00        1120.30    11.8
55            50.35         314.55     6.2
56            64.50        1888.45    29.3
57            19.40         529.80    27.3
58           104.80        7308.95    69.7
59           109.40        6252.70    57.2
60            50.30        2878.55    57.2
61            71.40        1212.10    17.0
62           116.00        8182.85    70.5
63            19.85          19.85     1.0
64            99.75          99.75     1.0
65            93.95        2861.45    30.5
66            90.80        1442.20    15.9
67            84.35        4059.35    48.1
68            58.25        4145.90    71.2
69           107.55        3645.50    33.9
70            19.95         187.75     9.4
71           111.20        2317.10    20.8
72            40.20        1448.80    36.0
73            85.80        2193.65    25.6
74            35.40        1748.90    49.4
75            73.85         511.25     6.9
76            88.10        5526.75    62.7
77           101.35        1553.95    15.3
78            45.80        1147.00    25.0
79            94.65        6747.35    71.3
80            20.50         865.05    42.2
81            89.40        5976.90    66.9
82            86.25         181.65     2.1
83            74.85        3268.05    43.7
84            89.75        1052.40    11.7
85           109.95        7634.25    69.4
86            80.20          80.20     1.0
87            19.85          63.75     3.2
88            90.35         190.50     2.1
89            86.45        2401.05    27.8
90            20.30         511.25    25.2
91           101.25        3949.15    39.0
92            94.70        2362.10    24.9
93            70.90          70.90     1.0
94            54.20        1152.70    21.3
95           114.90        8496.70    73.9
96            19.55         470.20    24.1
97            86.85        1564.40    18.0
98            25.35        1847.55    72.9
99           109.90        3694.70    33.6

In [34]:
float_cols_range = float_columns.max() - float_columns.min()
float_cols_range

monthly_charges      97.40
total_charges      8476.85
tenure               73.20
dtype: float64

## 6. Download your spreadsheet exercises google sheet as an excel file (File → Download → Microsoft Excel). 
### Read the Table1_CustDetails worksheet into a dataframe named df_excel.

In [36]:
df_excel = pd.read_excel("Fred Lindsey - jemison_spreadsheet_exercises.xlsx")
df_excel.head(5)

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,total_charges,churn,tenure
0,0002-ORFBO,Female,0.0,Yes,Yes,1.0,1.0,1.0,Mailed check,65.6,593.30,No,9.044207
1,0003-MKNFE,Male,0.0,No,No,2.0,1.0,0.0,Mailed check,59.9,542.40,No,9.055092
2,0004-TLHLJ,Male,0.0,No,No,1.0,2.0,0.0,Electronic check,73.9,280.85,Yes,3.800406
3,0011-IGKFF,Male,1.0,Yes,No,1.0,2.0,0.0,Electronic check,98.0,1237.85,Yes,12.631122
4,0013-EXCHZ,Female,1.0,Yes,No,1.0,2.0,0.0,Mailed check,83.9,267.40,Yes,3.187128

In [37]:
df_excel_sample = df_excel.head(100)
df_excel_sample

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,total_charges,churn,tenure
0,0002-ORFBO,Female,0.0,Yes,Yes,1.0,1.0,1.0,Mailed check,65.60,593.30,No,9.044207
1,0003-MKNFE,Male,0.0,No,No,2.0,1.0,0.0,Mailed check,59.90,542.40,No,9.055092
2,0004-TLHLJ,Male,0.0,No,No,1.0,2.0,0.0,Electronic check,73.90,280.85,Yes,3.800406
3,0011-IGKFF,Male,1.0,Yes,No,1.0,2.0,0.0,Electronic check,98.00,1237.85,Yes,12.631122
4,0013-EXCHZ,Female,1.0,Yes,No,1.0,2.0,0.0,Mailed check,83.90,267.40,Yes,3.187128
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0164-APGRB,Female,0.0,No,No,2.0,2.0,2.0,Electronic check,114.90,8496.70,No,73.948651
96,0164-XAIRP,Female,0.0,No,No,1.0,0.0,2.0,Bank transfer (automatic),19.55,470.20,No,24.051151
97,0168-XZKBB,Female,0.0,Yes,No,2.0,2.0,0.0,Electronic check,86.85,1564.40,No,18.012666
98,0174-QRVVY,Male,0.0,Yes,Yes,2.0,0.0,2.0,Credit card (automatic),25.35,1847.55,No,72.881657
99,0177-PXBAT,Male,1.0,Yes,No,2.0,2.0,0.0,Bank transfer (automatic),109.90,3694.70,No,33.618744

In [39]:
## print the first 5 column names
df_excel_sample.columns[0:5]

Index(['customer_id', 'gender', 'is_senior_citizen', 'partner', 'dependents'], dtype='object')

In [40]:
## print the data type of each column
obj_columns = list(df_excel_sample.select_dtypes(['object']))
obj_columns
#df_excel_sample.select_dtypes(include='object').to_list

['customer_id', 'gender', 'partner', 'dependents', 'payment_type', 'churn']

In [41]:
flt_cols = df_excel_sample.select_dtypes(['float'])
flt_cols_range = flt_cols.max() - flt_cols.min()
flt_cols_range

is_senior_citizen       1.000000
phone_service           2.000000
internet_service        2.000000
contract_type           2.000000
monthly_charges        97.400000
total_charges        8476.850000
tenure                 73.177334
dtype: float64

## 7. Read the data from this google sheet into a dataframe, df_google.

In [9]:
sheet_url = 'https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit#gid=341089357'    

csv_export_url = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')

df_google = pd.read_csv(csv_export_url)
df_google.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
## Print the first 3 rows
df_google.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [11]:
## Shape
df_google.shape

(891, 12)

In [12]:
## Column names
df_google.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [13]:
## Col data types
df_google.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [42]:
df_google.describe().T

,count,mean,std,min,25%,50%,75%,max
PassengerId,891.0,446.000000,257.353842,1.00,223.5000,446.0000,668.5,891.0000
Survived,891.0,0.383838,0.486592,0.00,0.0000,0.0000,1.0,1.0000
Pclass,891.0,2.308642,0.836071,1.00,2.0000,3.0000,3.0,3.0000
Age,714.0,29.699118,14.526497,0.42,20.1250,28.0000,38.0,80.0000
SibSp,891.0,0.523008,1.102743,0.00,0.0000,0.0000,1.0,8.0000
Parch,891.0,0.381594,0.806057,0.00,0.0000,0.0000,0.0,6.0000
Fare,891.0,32.204208,49.693429,0.00,7.9104,14.4542,31.0,512.3292

In [43]:
df_google.nunique()

# for col in df_google.columns:
#     if df_google[col].dtypes == 'object'

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

## 7. Titanic

In [16]:
import acquire as aq

df_titanic = aq.get_titanic_data()
df_titanic

,passenger_id,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,deck,embark_town,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,None,Southampton,0
1,1,1,1,female,38.0,1,0,71.2833,C,First,C,Cherbourg,0
2,2,1,3,female,26.0,0,0,7.9250,S,Third,None,Southampton,1
3,3,1,1,female,35.0,1,0,53.1000,S,First,C,Southampton,0
4,4,0,3,male,35.0,0,0,8.0500,S,Third,None,Southampton,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,0,2,male,27.0,0,0,13.0000,S,Second,None,Southampton,1
887,887,1,1,female,19.0,0,0,30.0000,S,First,B,Southampton,1
888,888,0,3,female,NaN,1,2,23.4500,S,Third,None,Southampton,0
889,889,1,1,male,26.0,0,0,30.0000,C,First,C,Cherbourg,1
890,890,0,3,male,32.0,0,0,7.7500,Q,Third,None,Queenstown,1

In [17]:
df_iris = aq.get_iris_db()
df_iris

   species_id species_name
0           1       setosa
1           2   versicolor
2           3    virginica

In [18]:
df_telco_churn = aq.get_telco_data()
df_telco_churn

,internet_service_type_id,payment_type_id,contract_type_id,customer_id,gender,senior_citizen,partner,dependents,tenure,phone_service,...,tech_support,streaming_tv,streaming_movies,paperless_billing,monthly_charges,total_charges,churn,contract_type,payment_type,internet_service_type
0,1,2,2,0002-ORFBO,Female,0,Yes,Yes,9,Yes,...,Yes,Yes,No,Yes,65.60,593.3,No,One year,Mailed check,DSL
1,1,2,1,0003-MKNFE,Male,0,No,No,9,Yes,...,No,No,Yes,No,59.90,542.4,No,Month-to-month,Mailed check,DSL
2,2,1,1,0004-TLHLJ,Male,0,No,No,4,Yes,...,No,No,No,Yes,73.90,280.85,Yes,Month-to-month,Electronic check,Fiber optic
3,2,1,1,0011-IGKFF,Male,1,Yes,No,13,Yes,...,No,Yes,Yes,Yes,98.00,1237.85,Yes,Month-to-month,Electronic check,Fiber optic
4,2,2,1,0013-EXCHZ,Female,1,Yes,No,3,Yes,...,Yes,Yes,No,Yes,83.90,267.4,Yes,Month-to-month,Mailed check,Fiber optic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,2,2,9987-LUTYD,Female,0,No,No,13,Yes,...,Yes,No,No,No,55.15,742.9,No,One year,Mailed check,DSL
7039,2,1,1,9992-RRAMN,Male,0,Yes,No,22,Yes,...,No,No,Yes,Yes,85.10,1873.7,Yes,Month-to-month,Electronic check,Fiber optic
7040,1,2,1,9992-UJOEL,Male,0,No,No,2,Yes,...,No,No,No,Yes,50.30,92.75,No,Month-to-month,Mailed check,DSL
7041,1,2,3,9993-LHIEB,Male,0,Yes,Yes,67,Yes,...,Yes,No,Yes,No,67.85,4627.65,No,Two year,Mailed check,DSL
7042,1,1,3,9995-HOTOH,Male,0,Yes,Yes,63,No,...,No,Yes,Yes,No,59.00,3707.6,No,Two year,Electronic check,DSL